version: "3"
networks:
  app-tier:
    driver: bridge
services:
  redis:
    container_name: newsdict-redis
    image: 'redis'
    networks:
      - app-tier
  mongo:
    container_name: newsdict-mongodb
    image: mongo
    restart: always
    ports:
      - ${LOCAL_MONGODB_PORT}:27017
    networks:
      - app-tier
    volumes:
      - ./tmp/data:/data
  web:
    tty: true
    stdin_open: true
    container_name: newsdict-web
    build:
      context: .
      dockerfile: Dockerfile
    image: newsdictio
    volumes:
      - ./:/var/www/docker
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/web/startup.sh"
    ports:
      - 3000:80
      - 3035:3036
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: newsdict-worker
    image: newsdictio
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/worker/startup.sh"
    volumes:
      - ./:/var/www/docker
    networks:
      - app-tier
    depends_on:
      - web
      - redis
  document:
    tty: true
    stdin_open: true
    container_name: newsdict-document
    image: newsdictio
    command: "bash src/provisioning/startup/document/startup.sh"
    volumes:
      - ./:/var/www/docker
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - web