version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  redis:
    container_name: redis
    image: 'redis'
    networks:
      - app-tier
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - app-tier
    volumes:
      - ./tmp/data:/data
  web:
    tty: true
    stdin_open: true
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    image: newsdictio
    volumes:
      - ./:/var/www/docker:cached
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/web/startup.sh development"
    ports:
      - 3100:3000
    networks:
      - app-tier
  webpack-dev-server:
    tty: true
    stdin_open: true
    container_name: webpack-dev-server
    build:
      context: .
      dockerfile: Dockerfile
    image: newsdictio
    volumes:
      - ./:/var/www/docker:cached
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/webpack-dev-server/startup.sh development"
    ports:
      - 3035:3035
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: worker
    image: newsdictio
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/worker/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    networks:
      - app-tier
    depends_on:
      - web
  asciidoctor:
    tty: true
    stdin_open: true
    container_name: asciidoctor
    image: newsdict/asciidoctor.live:v0.1.12
    command: "bash src/provisioning/startup/asciidoctor/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    ports:
      - 8080:80
    networks:
      - app-tier
    depends_on:
      - web
  guard:
    tty: true
    stdin_open: true
    container_name: guard
    image: newsdict/asciidoctor.live:v0.1.12
    command: "bash src/provisioning/startup/guard/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    networks:
      - app-tier
    depends_on:
      - web
  browser-sync:
    tty: true
    stdin_open: true
    container_name: browser-sync
    image: newsdict/asciidoctor.live:v0.1.12
    command: "bash src/provisioning/startup/browser-sync/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - app-tier
    depends_on:
      - web