version: "3"
networks:
  app-tier:
    driver: bridge
services:
  redis:
    container_name: newsdict_redis
    image: 'redis'
    networks:
      - app-tier
  mongo:
    container_name: newsdict_mongodb
    image: mongo
    restart: always
    ports:
      - ${LOCAL_MONGODB_PORT}:27017
    networks:
      - app-tier
  web:
    tty: true
    stdin_open: true
    container_name: newsdict_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/docker
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/web/startup.sh"
    ports:
      - 3000:80
      - 3035:3036
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: newsdict_worker
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/worker/startup.sh"
    volumes:
    - ./:/var/www/docker
    networks:
      - app-tier
    depends_on:
      - web
      - redis
  document:
    tty: true
    stdin_open: true
    container_name: newsdict_document
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/document/startup.sh"
    volumes:
      - ./:/var/www/docker
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - web