version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  redis:
    container_name: ${NAMESPACE}_redis
    image: 'redis'
    networks:
      - app-tier
  mongodb:
    container_name: ${NAMESPACE}_mongodb
    image: mongo
    restart: always
    networks:
      - app-tier
    volumes:
      - ~/mongodb:/data/db
  web:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_web
    build:
      context: .
      dockerfile: Dockerfile
    image: newsdictio
    volumes:
      - ./:/var/www/docker:cached
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/web/startup.sh development"
    ports:
      - 3100:3000
      - 3035:3035
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_worker
    image: newsdictio
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/worker/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    networks:
      - app-tier
    depends_on:
      - web
  bundle:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_bundle
    image: newsdictio
    volumes:
      - ./:/var/www/docker:cached
    working_dir: /var/www/docker
    command: "bash src/provisioning/startup/bundle/startup.sh development"
    networks:
      - app-tier
  asciidoctor:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_asciidoctor
    image: newsdict/asciidoctor.live:v0.1.18
    command: "bash src/provisioning/startup/asciidoctor/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    ports:
      - 8080:80
    networks:
      - app-tier
    depends_on:
      - web
  guard:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_guard
    image: newsdict/asciidoctor.live:v0.1.18
    command: "bash src/provisioning/startup/guard/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    networks:
      - app-tier
    depends_on:
      - web
  browser-sync:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_browser-sync
    image: newsdict/asciidoctor.live:v0.1.18
    command: "bash src/provisioning/startup/browser-sync/startup.sh development"
    volumes:
      - ./:/var/www/docker:cached
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - app-tier
    depends_on:
      - web