version: "2"
networks:
  app-tier:
    driver: bridge
services:
  redis:
    container_name: newsdict_redis
    image: 'redis'
    networks:
      - app-tier
  mongo:
    container_name: newsdict_mongodb
    image: mongo
    restart: always
    networks:
      - app-tier
  web:
    tty: true
    stdin_open: true
    container_name: newsdict_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/newsdict
    working_dir: /var/www/newsdict
    command: >
      bash -c "yarn install --check-files
      && bundle install --path .bundle --no-deployment --with development test
      && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports: 
      - 3000:3000
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: newsdict_worker
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/newsdict
    command: "bundle exec sidekiq -q default"
    volumes:
    - ./:/var/www/newsdict
    networks:
      - app-tier