version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: set .env
          command: |
            cp .env-sample .env
      - run:
          name: docker-compose down
          command: |
            docker-compose down
      - run:
          name: build & rails test -v
          command: |
            set -x
            docker-compose --project-name newsdict build web
            docker-compose up -d
            docker-compose exec web /bin/bash -c "bash src/provisioning/startup/test/test.sh"
      - run:
          name: docker-compose down
          command: docker-compose down