development:
  # Configure available database clients. (required)
  clients:
    default:
      database: <%= ENV['NAMESPACE'] %>_development
      hosts:
        - mongodb:27017
  options: &options
    raise_not_found_error: false
    use_activesupport_time_zone: true
test:
  clients:
    default:
      database: <%= ENV['NAMESPACE'] %>_test
      hosts:
        - mongodb:27017
  options:
    <<: *options
document:
  clients:
    default:
      database: <%= ENV['NAMESPACE'] %>_document
      hosts:
        - mongodb:27017
  options:
    <<: *options
production:
  clients:
    default:
      database: <%= ENV['NAMESPACE'] %>_production
      hosts:
        - <%= ENV['MONGODB_HOST'] %>
  options:
    <<: *options

