development:
  # Configure available database clients. (required)
  clients:
    default:
      database: newsdict_development
      hosts:
        - mongo:27017
  options: &options
    raise_not_found_error: false
test:
  clients:
    default:
      database: newsdict_test
      hosts:
        - mongo:27017
  options:
    <<: *options
document:
  clients:
    default:
      database: newsdict_document
      hosts:
        - mongo:27017
  options:
    <<: *options
production:
  clients:
    default:
      database: newsdict_production
      hosts:
        - <%= ENV['MONGODB_HOST'] %>
  options:
    <<: *options

