:schedule:
  web_sites_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crowling::WebSitesJob
  twitter_accounts_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crowling::TwitterAccountsJob
  update_mecab_dics_job:
    enabled: false
    cron: '0 0 0 * * *'
    class: UpdateMecabDicsJob
  sitemaps_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: SitemapsJob
  notify_chatworks_job:
    enabled: true
    cron: '0 * * * * *'
    class: Notify::ChatworksJob