:schedule:
  web_urls_job:
    enabled: false
    cron: '0 */3 * * *'
    class: Crowling::WebUrlsJob
  web_sections_job:
    enabled: false
    cron: '0 */3 * * *'
    class: Crowling::WebSectionsJob
  twitter_account_job:
    enabled: false
    cron: '0 */3 * * *'
    class: Crowling::TwitterAccountsJob
  update_mecab_dic_job:
    enabled: false
    cron: '0 0 * * * *'
    class: UpdateMecabDicsJob
  sitemap_job:
    enabled: false
    cron: '0 0 0 * * *'
    class: SitemapsJob