:schedule:
  urls_job:
    enabled: false
    class: UrlsJob
  twitter_account_job:
    enabled: true
    cron: '0 */3 * * *'
    class: TwitterAccountsJob
  update_mecab_dic_job:
    enabled: true
    cron: '0 0 * * * *'
    class: UpdateMecabDicsJob
  sitemap_job:
    enabled: true
    cron: '0 0 0 * * *'
    class: SitemapsJob