:schedule:
  web_sites_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crawler::WebSitesJob
  twitter_accounts_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crawler::TwitterAccountsJob
  mecab_dics_job:
    enabled: false
    cron: '0 0 0 * * *'
    class: MecabDicsJob
  sitemaps_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: SitemapsJob
  notify_chatworks_job:
    enabled: true
    cron: '0 * * * * *'
    class: Notify::ChatworksJob
  notify_slacks_job:
    enabled: true
    cron: '0 * * * * *'
    class: Notify::SlacksJob