development: &development
  # Minimum number of characters to detect meta title
  min_length_of_meta_title: 10
  # Split regular expression for titles
  regex_to_sprit_title: '\||-|:|｜|：|〜|\~| – '
  # User Agent
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) web_stat gem agent"
  # Eyecatch image xpaths
  eyecatch_image_xpaths:
    - '/html/head/meta[@property="twitter:image"]/@content'
    - '/html/head/meta[@property="og:image"]/@content'
    - '//img[@class="attachment-post-thumbnail"]/@src'
    - '//div[@id="content"]//img/@src'
    - '//img/@src'
  thumbnail_regex:
    youtube:
      - '%r{^https://www.youtube.com/watch\?v=([^&]+)}'
      - 'http://img.youtube.com/vi/\1/default.jpg'
  userdic: ""
  use_chromedirver: false
test:
  <<: *development
production:
  <<: *development
  use_chromedirver: true