name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker Compose
      run: |
        set -x
        curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - name: Set up .env
      run: |
        cp .env-test .env
    - name: DockerCompose down
      run: |
        docker-compose down
    - name: build & rails test -v
      run: |
        set -xe
        docker/start -d
        docker/rails test -v
    - name: DockerCompose down
      run: |
        docker-compose down
