name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Docker Compose
      run: |
        set -xe
        curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - name: Set up .env
      run: |
        cp .env-test .env
    - name: build
      run: |
        set -xe
        docker/start --build
    - name: rails test -v
      run: |
        set -xe
        docker/rails test -v
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#cdcdd1'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Passed unittest :rocket:'
        SLACK_TITLE: Passed UnitTest
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#3278bd'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Start unittest :100:'
        SLACK_TITLE: UnitTest
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}